# Generated by Django 5.1.7 on 2025-06-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_parameterblending_parameteroptpembebanan_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('penanggungjawab', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
