# Generated by Django 5.1.7 on 2025-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_profile_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pendanaan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
