# Generated by Django 5.1.7 on 2025-06-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_project_pendanaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyekDariEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('mulai', models.DateField()),
                ('selesai', models.DateField()),
                ('penanggungjawab', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('pendanaan', models.IntegerField()),
                ('aktivitas1', models.CharField(max_length=100)),
                ('aktivitas2', models.CharField(max_length=100)),
                ('aktivitas3', models.CharField(max_length=100)),
            ],
        ),
    ]
