# Generated by Django 5.1.7 on 2025-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_proyekdariengineering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyekDariEngineering',
        ),
        migrations.AddField(
            model_name='project',
            name='aktivitas1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aktivitas2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aktivitas3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
