# Generated by Django 5.1.7 on 2025-06-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_delete_proyekdariengineering_project_aktivitas1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='mulai',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='pelaksana',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='selesai',
        ),
        migrations.AddField(
            model_name='timeline',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='status',
            field=models.IntegerField(),
        ),
    ]
