# Generated by Django 5.1.7 on 2025-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_remove_timeline_mulai_remove_timeline_pelaksana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='file_pdfs/'),
        ),
    ]
