# Generated by Django 5.1.7 on 2025-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=100)),
                ('nama_model', models.CharField(default='default_model', max_length=100)),
                ('status_model', models.CharField(max_length=100)),
                ('deskripsi_model', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploaded_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
