# Generated by Django 4.2.23 on 2025-06-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0011_projectmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKelompok', models.TextField()),
                ('deskripsi', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
