# Generated by Django 5.2.3 on 2025-06-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0012_managementsi_modelmasuk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanagement',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectmanagement',
            name='nama_model',
        ),
    ]
