# Generated by Django 5.2.3 on 2025-06-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0013_remove_projectmanagement_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='file_pdf',
        ),
    ]
